LiUSemWeb/HeFQUIN

- src/main/java/se/liu/ida/hefquin/federation/access/impl/iface/BRTPFInterfaceImpl.java
- src/main/java/se/liu/ida/hefquin/queryplan/executable/impl/ops/ExecOpBindJoinBRTPF.java
- src/main/java/se/liu/ida/hefquin/queryplan/executable/impl/ops/ExecOpGenericBindJoin.java
- src/main/java/se/liu/ida/hefquin/queryplan/executable/impl/ops/ExecOpGenericBindJoinWithTriplesRequests.java
- src/main/java/se/liu/ida/hefquin/queryplan/physical/impl/PhysicalOpBindJoin.java
- src/test/java/se/liu/ida/hefquin/queryplan/executable/impl/ops/ExecOpBindJoinBRTPFTest.java
- src/test/java/se/liu/ida/hefquin/queryplan/executable/impl/ops/ExecOpTestBase.java
Include an executable bind join operator for BrTPF, corresponding physical operator, and a test script for ExecOpBindJoinBRTPF
> Bind-join for BrTPF

- src/main/java/se/liu/ida/hefquin/engine/data/impl/SolutionMappingUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwiithFILTER.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTER.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithFILTER.java
- src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTERTest.java
There might be room for optimisation and improvement, especially when creating the filter operation.
> Filter bind join

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/QueryOptimizationContext.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/costmodel/CostModelImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/greedy/GreedyEnumeration.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/greedy/GreedyQueryOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/CostEstimationUtils.java
- src/main/java/se/liu/ida/hefquin/jenaintegration/sparql/engine/main/OpExecutorHeFQUIN.java
- src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImplTest.java
> Uses cost estimates to compare plans in the greedy enumeration algorithm

- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/LPG2RDFConfiguration.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslator.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/DefaultConfiguration.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/EdgeLabelCondition.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/NodeLabelCondition.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/LabelsReturnStatement.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryBuilder.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/SPARQLStar2CypherTranslator.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java
I still need to do a last thorough check to compare with the rules on the paper, but this should be very close.
> Triple pattern translation

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/GreedyJoinPlanOptimizerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/JoinPlanOptimizer.java
"subplans.remove (indexOfBestPlan);" throw an UnsupportedOperationException.
Hence, change 'subplans' from a static List to a LinkedList
> Fix an issue in Greedy Algorithm

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/IterativeImprovementBasedQueryOptimizer.java
@hartig The test gets an error (which is different from it just failing the test, right?) when I try a basic use of the Randomizer.
How do I debug errors in the test?
> Interative Improvement Query Optimization Algorithm

- src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java
Support getting the number of elements (RDF terms/ variables) from SPARQL patterns (contain AND and FILTER)
> Fix issues in query pattern utils

- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/FilterEmptyPropertyListsCondition.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/Record2SolutionMappingTranslationTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java
Fixes the case where a query would return empty lists if no property had a given value.
> Filter empty lists

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/evolutionaryAlgorithm/EvolutionaryAlgorithmQueryOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/EquilibriumConditionByRelativeSubplanCount.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/EquilibriumConditionForSimulatedAnnealing.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/IterativeImprovementBasedQueryOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/RandomizedQueryOptimizerBase.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/SimulatedAnnealing.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/PlanRewritingUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/PhysicalPlanWithCostUtils.java
I've edited a bit in the base class, which I want to use for all three algorithms.
Because of this, I've decided to create this is as my common branch. To make things easier for you to know what is what and keep order, I will create branches for each of the algorithms _out of this branch_. I'm also going to start working on two-phase optimization (2PO) soon, and I'll likely look back and forth a lot between all of the algorithms as I want to possibly have the Iterative and Annealing algorithms have an optimize function which is static and ideal for use in the 2PO in a way that the 2PO becomes sufficiently usable with different settings (input values to the 2PO will include things such as how many generations II will run before SA takes over, etc).
> Randomized Algorithms for Optimizing Large Join Queries

- src/main/java/se/liu/ida/hefquin/engine/data/utils/SolutionMappingUtils.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/BRTPFInterface.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/TPFInterface.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/BRTPFInterfaceImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/TPFInterfaceImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/BRTPFRequestProcessorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorBase.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/response/TPFResponseBuilder.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/response/TPFResponseImpl.java
- src/test/java/se/liu/ida/hefquin/engine/EngineTestBase.java
- src/test/java/se/liu/ida/hefquin/engine/data/utils/SolutionMappingUtilsTest.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerBase1Test.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorImplTest.java
> Implementation of TPFRequestProcessor

- src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineBuilder.java
- src/main/java/se/liu/ida/hefquin/engine/data/utils/TriplesToSolMapsConverter.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/BRTPFRequest.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/TPFRequest.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/TPFResponse.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/BRTPFInterfaceImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/TPFInterfaceImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/req/BRTPFRequestImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/req/TPFRequestImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/response/TPFResponseImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/utils/FederationAccessUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpGenericRequestWithTPFPaging.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpGenericTriplePatternRequestWithTPF.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestBRTPF.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanFactory.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/cardinality/CardinalityEstimationImpl.java
- src/test/java/se/liu/ida/hefquin/engine/EngineTestBase.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/AsyncFederationAccessManagerImplTest.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerBase1Test.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerWithCacheTest.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorImplTest.java
- src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestTPFatTPFServerTest.java
closes #145
@chengsijin0817 I am done with adding correct support for TPF paging :-)
> Correct implementation of TPF paging

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/evolutionaryAlgorithm/EvolutionaryAlgorithmQueryOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/evolutionaryAlgorithm/Generation.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/evolutionaryAlgorithm/InitializeNrGeneration.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/evolutionaryAlgorithm/TerminateByDistancePercAvgDynamicG.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/PhysicalPlanWithCostUtils.java
Add an implementation of termination criteria, which examines the distance of average cost for a number of generations. The number of generations for checking depends on the number of lowest-cost plans in each generation.
> Add an implementation of termination criteria

- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalOpConverter.java
Additional functionality added to LogicalToPhysicalOpConverter. This was just a matter of a few lines as far as I can see, so I'm worried that I missed something.
> Logical to physical filter conversion.

- src/main/java/se/liu/ida/hefquin/engine/federation/access/JSONResponse.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/GraphQLRequestProcessorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/response/JSONResponseImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/query/GraphQLQuery.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/query/impl/GraphQLQueryImpl.java
- src/test/java/se/liu/ida/hefquin/engine/EngineTestBase.java
- src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/GraphQLRequestProcessorImplTest.java
Implementation of GraphQLRequestProcessor with its related interfaces etc.
> GraphQLRequestProcessor Implementation with related interfaces

- src/main/java/se/liu/ida/hefquin/engine/data/impl/VocabularyMappingImpl.java
- src/test/java/se/liu/ida/hefquin/engine/data/impl/VocabularyMappingTest.java
Removed union and intersection as possibilities for Predicate translation and fixed the test accordingly
> Fixed approach of VocabularyMappingImpl

- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestBRTPFWithTranslation.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpRequest.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpRequestWithTranslation.java
Again mostly the same as ExecOpRequestTPFatTPFServer but using BRTPFRequest
> ExecOpRequestBRTPFWithTranslation

- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpGlobalToLocal.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitor.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitorBase.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalOpGlobalToLocal.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlanVisitor.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpGlobalToLocal.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalPlanPrinter.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanPrinter.java
The same thing that was done for LocalToGlobal, but for GlobalToLocal.
> GlobalToLocal operators, with printer and visitor methods.

- src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java
- src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineBuilder.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/QueryPlanningStats.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/planning/QueryPlannerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/planning/QueryPlanningStatsImpl.java
- src/main/java/se/liu/ida/hefquin/jenaintegration/sparql/HeFQUINConstants.java
- src/main/java/se/liu/ida/hefquin/jenaintegration/sparql/engine/main/OpExecutorHeFQUIN.java
- src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImplTest.java
> Print plans from the CLI

- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/BaseForExecOpBindJoin.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/BaseForExecOpBindJoinSPARQL.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/BaseForExecOpBindJoinWithRequestOps.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinBRTPF.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTER.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTERandTranslation.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithUNION.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUES.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpParallelMultiwayLeftJoin.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithFILTER.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithFILTERandTranslation.java
- src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTERandTranslationTest.java
> Robust bind join implementation

- src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/SPARQLRequestProcessorImpl.java
> Own code to handle the HTTP access to SPARQL endpoints

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/HeuristicForLogicalOptimization.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/LogicalOptimizerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/UnionPullUp.java
- src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/UnionPullUpTest.java
@chengsijin0817 here you go :-)
In case you want to disable the heuristic, you have to comment out line 16 in `LogicalOptimizerImpl`
> 'UnionPullUp' as a first heuristic for logical query optimization

- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/SPARQL2GraphQLTranslator.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/impl/GraphQLEndpointInitializerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/impl/SPARQL2GraphQLTranslatorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/utils/GraphQLQueryRootForStarPattern.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/utils/QueryTranslatingException.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/SPARQL2GraphQLTranslatorTest.java
Some small fixes to the endpoint initializer and SPARQL2GraphQL translator.
> small fixes to endpoint initializer and SPARQL2GraphQL translator

- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslator.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java
This PR contains the restricted versions of the translation rules, depending on the different boundedness properties. Tests are also included.
> Restricted translations

- src/main/java/se/liu/ida/hefquin/engine/data/mappings/impl/EntityMappingImpl.java
- src/test/java/se/liu/ida/hefquin/engine/data/mappings/impl/EntityMappingImplTest.java
Checkpointing to take a break.
For applying to TriplePattern, I've assumed that any of (subject, predicate, object) can be a URI.
I'm not quite sure exactly how I'm going to tackle the SolutionMapping methods.
As far as I understand it by looking at code, SolutionMapping contains one binding.
The binding can contain any number of nodes, bound to different variables.
Each node, if it is a URI, can have any number of nodes mapped to them in the g2lMap and l2gMap respectively.
Is this correct? @hartig @chengsijin0817
> EntityMappingImpl

- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/ApplyVocabularyMappings.java
Initial commits, checkpointing for the night.
> rewriteLogPlan

- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/DefaultConfiguration.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/LabelsExpression.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/LiteralExpression.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryCombinator.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java
This PR contains several bug fixes found during the experimentation, and adds a missing rule. Each commit message explains the different fixes.
> LPG-wrapper fix

- src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/utils/SPARQL2GraphQLHelper.java
Just adding a small safety check before adding fields to the GraphQL query. 
Doesn't affect my current performance test queries.
I re-ran my performance tests for this specific part and there was basically no difference.
> small safety check to SPARQL2GraphQLTranslator

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/cardinality/CardinalityEstimationImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/cardinality/VarSpecificCardinalityEstimationImpl.java
- The cardinality of a subquery is the maximum cardinality of the all certain variables
- The variable-specific cardinality in a subquery is calculated based on the cardinality of its subqueries.
> Update cardinality estimation

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/rewriting/RuleInstances.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/rewriting/rules/IdentifyTypeOfRequestUsedForReq.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/rewriting/rules/RuleConvertUnionOfTwoJoinsToJoinOfUnion.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/rewriting/rules/RuleMergeJoinOfTwoPatternReqIntoOneReq.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/rewriting/rules/RuleMergeUNIONOfTwoPatternReqIntoOneReq.java
Divide rewriting rules into groups, which makes it possible to apply partial rules in optimization
> Rewriting rules

- src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java
- getVariablesInPattern ( final SPARQLGraphPattern queryPattern )
- getNumberOfVarOccurrences ( final SPARQLGraphPattern queryPattern )
- and getNumberOfTermOccurrences ( final SPARQLGraphPattern queryPattern )
> Consider UnionGraphPattern and GroupGraphPattern in QueryPatternUtils

- src/main/java/se/liu/ida/hefquin/engine/query/impl/SPARQLGroupPatternImpl.java
- src/main/java/se/liu/ida/hefquin/engine/query/impl/SPARQLUnionPatternImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/cardinality/CardinalityEstimationImpl.java
**Issue**: physical plans that contain SPARQLUnionPattern or SPARQLGroupPattern are not printed correctly.
**Solution**: Implement toString() in SPARQLUnionPatternImpl and SPARQLGroupPatternImpl
> Physical plan printer

- src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalPlanPrinter.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/LogicalOptimizerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/GreedyBasedReordering.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/formula/FmAwareWeightedJoinAndUnboundVariableCount.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/formula/Formula.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/formula/FormulaForComputingSelectivity.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/formula/JoinAwareWeightedUnboundVariableCount.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/utils/JoinAnalyzer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/utils/QueryAnalyzer.java
Implement a federation-member-aware heuristic for join reordering of federated SPARQL query
> Fm aware join ordering heuristic

- src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfig.java
- src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanFactory.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/GreedyBasedReordering.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedBushyJoinPlanOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedJoinPlanOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedLinearJoinPlanOptimizer.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/GreedyJoinPlanOptimizerImpl.java
- src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedOptimizerHelperTest.java
Two versions of the DP optimizer: 
- one considers left join trees only
- another has the potential to generate a bushy tree
> Two DP based optimizers

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/LogicalOptimizerImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/cardinality/MinBasedCardinalityEstimationImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/cardinality/VarSpecificCardinalityEstimationImpl.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfRequests.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfTermsShippedInRequests.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfTermsShippedInResponses.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfVarsShippedInRequests.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfVarsShippedInResponses.java
Now applying vocabulary mappings is supported by all available algorithms (except for the evolutionary algorithm)
> Extend cost model to consider vocabulary mapping

- src/main/java/se/liu/ida/hefquin/engine/data/VocabularyMapping.java
- src/main/java/se/liu/ida/hefquin/engine/data/impl/VocabularyMappingImpl.java
- src/main/java/se/liu/ida/hefquin/engine/data/mappings/impl/VocabularyMappingWrappingImpl.java
- src/main/java/se/liu/ida/hefquin/engine/federation/catalog/FederationDescriptionReader.java
- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/ApplyVocabularyMappings.java
Extend the VocabularyMapping interface with a boolean-typed function called isEquivalenceOnly()
> Extend the VocabularyMapping

- src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/PushJoinUnderUnionWithRequests.java
Consider the operator LogicalOpLocalToGlobal when pushing join under union with requests
> Update the implementation of 'PushJoinUnderUnionWithRequests'

- src/main/java/se/liu/ida/hefquin/engine/federation/catalog/FederationDescriptionReader.java
- src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java
Use schema mapping and entity mapping when parsing the vocabulary mapping file
> Use schema mapping&entity mapping

- src/main/java/se/liu/ida/hefquin/cli/RunBGPOverNeo4j.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeMapping.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeMappingToBNodesImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeMappingToURIsImpl.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/NodeMappingToBNodesImplTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/NodeMappingToURIsImplTest.java
Encapsulate map/unmap Node.
Add unit test for NodeMappingToUTIsImpl and NodeMappingToURIsImpl class.
> Encapsulate map/unmap Node

- ExampleLPG2RDF.ttl
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
- src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
Add LPG2RDFConfigurationReader
Add test for LPG2RDFConfigurationReader
> Add LPG2RDFConfigurationReader

- ExampleLPG2RDF.ttl
- src/main/java/se/liu/ida/hefquin/cli/RunBGPOverNeo4j.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMapping.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToLiteralsImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToURIsImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeMappingToBNodesImpl.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeMappingToURIsImpl.java
- src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToLiteralsImplTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToURIsImplTest.java
Add NodeLabelMapping Class
Add test for NodeLabelMapping children Classes
Modify LPG2RDFConfigurationReader to use NodeLabelMapping.
Modify LPG2RDFConfigurationReaderTest to test NodeLabelMapping
> Add NodeLabelMapping Class

- ExampleLPG2RDF.ttl
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedEdgeLabelMappingToURIsImpl.java
- src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedEdgeLabelMappingToURIsImplTest.java
Add RegexBasedEdgeLabelMapping and its tests.
> Add RegexBasedEdgeLabelMapping and its tests

- ExampleLPG2RDF.ttl
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
- src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleEdgeLabelMappingToURIsImpl.java
- src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
- src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleEdgeLabelMappingToURIsImplTest.java
Add SingleEdgeLabelMapping and its tests.
> Add SingleEdgeLabelMapping and its tests

- src/main/java/se/liu/ida/hefquin/cli/MaterializeRDFViewOfLPG.java
I have created two Cypher queries to fetch data from Neo4j and translate the results. However, results handling has remained. 
Could you please take a look at the implementation? 
I am not quite sure about the way to return the results.
Please guide me on how to handle this. 
Thanks!
> Get data from neo4j and translate data

- src/main/resources/DefaultEngineConf.ttl
- src/test/resources/TestEngineConf.ttl
Fixes the test failure that occurred in the following CI job after merging PR #338
https://github.com/LiUSemWeb/HeFQUIN/actions/runs/10506844473/job/29107342776
> use updated engine conf files in the 'resources' directories

- hefquin-base/src/main/java/se/liu/ida/hefquin/base/data/utils/ExtendIteratorForSolMaps_MultipleVars.java
- hefquin-base/src/main/java/se/liu/ida/hefquin/base/data/utils/ExtendIteratorForSolMaps_OneVar.java
- hefquin-base/src/test/java/se/liu/ida/hefquin/base/data/utils/ExtendIteratorForSolMaps_MultipleVarsTest.java
- hefquin-base/src/test/java/se/liu/ida/hefquin/base/data/utils/ExtendIteratorForSolMaps_OneVarTest.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/ValuesServiceQueryResolver.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBind.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlanVisitor.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBind.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalOpConverter.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/TextBasedLogicalPlanPrinterImpl.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/TextBasedPhysicalPlanPrinterImpl.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/ApplyVocabularyMappings.java
- hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/ValuesServiceQueryResolverTest.java
- hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindTest.java
> Adds support for BIND and fixes ValuesServiceQueryResolver

- hefquin-base/pom.xml
- hefquin-cli/pom.xml
- hefquin-engine/pom.xml
- hefquin-graphqlconnector/pom.xml
- hefquin-pgconnector/pom.xml
- hefquin-service/pom.xml
I am creating a first release, primarily to get some experience with the release process, to check that the wiki page that describes the process is correct (https://github.com/LiUSemWeb/HeFQUIN/wiki/Release-Logistics), and to make sure publishing to Maven Central works (in which case we can close issue #365).
> bump up version to 0.0.4

- hefquin-base/src/main/java/se/liu/ida/hefquin/base/query/impl/QueryPatternUtils.java
- hefquin-base/src/main/java/se/liu/ida/hefquin/base/utils/StatsPrinter.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUESorFILTER.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/pushbased/PushBasedExecPlanTaskBase.java
.. and some code cleanup.
This is related to the issue mentioned in https://github.com/LiUSemWeb/HeFQUIN/issues/411#issuecomment-2817579046
> Adds support for BIND during query planning

- hefquin-base/src/main/java/se/liu/ida/hefquin/base/data/utils/SolutionMappingUtils.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/BaseForExecOpBindJoinWithRequestOps.java
- hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithBoundJoin.java
- hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithBoundJoinTest.java
- hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/TestsForTPAddAlgorithms.java
Implementation of the bound-join algorithm, which uses variable renaming to minimize the number of requests (see issue https://github.com/LiUSemWeb/HeFQUIN/issues/344)
> 344 change algorithm of union based bind join
