src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java
src/main/java/se/liu/ida/hefquin/engine/datastructures/impl/cache/CacheEntryBaseFactory.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerWithCache.java
src/test/java/se/liu/ida/hefquin/engine/datastructures/impl/cache/GenericCacheImplTest.java
src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/AsyncFederationAccessManagerImplTest.java
src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerBase1Test.java
src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/FederationAccessManagerWithCacheTest.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/cardinality/CardinalityEstimationImplTest.java

Uses the `Cache` data structure for `FederationAccessManagerWithCache`. This is the minimum needed for #88.
/cc @chengsijin0817

Federation access manager with cache

---

src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java

When getting the number of elements from a SPARQL patterns: org.apache.jena.sparql.algebra.op.OpBGP is not captured by the condition ( queryPattern instanceof BGP), so update the condition to ( queryPattern.asJenaOp() instanceof OpBGP).

Fix an issue in QueryPatternUtils

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/SimulatedAnnealing.java

Simulated Annealing almost done, but I am at a loss for how to implement Equilibrium. It's supposed to be a boolean from what I can read in the paper, but the paper's example implementation defines it to be 16*(number or joins in query). (table 2.2, page 314 in the paper, page 3 in the pdf)
I also have some thoughts (see comments in code) of a small 'issue' (whose consequences are just that a couple of code lines appear to be inefficient in its implementation) concerning the selection of a random neighbour and the creation of PhysicalPlanWithCost objects. Since my proposed solution is to introduce a new constructor for PhysicalPlanWithCost, your input is necessary. @hartig

Simulated Annealing Query Optimization Algorithm

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/IdentifyTypeOfRequestUsedForReq.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleChangeOrderAndMergeJoinOfBGPReqIntoBGPAdd.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleDivideBGPAddToMultiTPAdd.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleDivideBGPReqIntoJoinOfTPReqs.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleDivideBGPReqIntoMultiTPAdds.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleMergeJoinOfOneBGPReqIntoBGPAdd.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/DPBasedJoinPlanOptimizer.java

This pull request is to address a problem that the applicable rewrite rules identified are incomplete. Specifically, the evolutionary algorithm fails to identify rewriting rules related to decomposing/rewriting Basic Graph Pattern.
Reason: the initial logical query is created by the method createSourceAssignment.createPlan(), which uses SPARQLRequest as the default type of request. Hence, it can't be captured by checking whether the root operator is a BGPRequest. 
To enable these rewriting rules (related to BGP), it should also consider cases where the root operator is a SPARQLRequest but the pattern is BasicPattern.
Solution: Add another method, isGraphPatternReqWithBGP(), to check whether the request is a SPARQL request with BasicPattern, and then update the relevant rewrite rules.

Identify SPARQL request with basic pattern

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java

Create an empty ElementGroup and then addElement to the ElementGroup.
Reason: class org.apache.jena.sparql.syntax.ElementPathBlock cannot be cast to class org.apache.jena.sparql.syntax.ElementGroup

Fix a bug in the method createNewGraphPatternWithAND()

---

src/main/java/se/liu/ida/hefquin/engine/query/impl/TriplePatternImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTER.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithUNION.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUES.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpGenericBindJoinWithRequestOps.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithFILTER.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithUNION.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpBindJoinWithVALUES.java

Extend three executable operators to make them applicable to SPARQL query patterns

Extend unary executable operators

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/randomized/IterativeImprovementBasedQueryOptimizer.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/randomized/IterativeImprovementBasedQueryOptimizerTest.java

I'm trying out using a SimpleJoinOrderingQueryOptimizer with a Randomized as its join-plan-optimizer as per your instructions, but I'm getting an error in the test due to some operation returning null. Since I don't quite understand how the joins work on a low-level I'm having trouble scratching my brain as to what is causing this error.

Using Randomized for IterativeImprovement

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpIndexNestedLoopsJoin.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanFactory.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/DPBasedJoinPlanOptimizer.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/GreedyJoinPlanOptimizerImpl.java

1. Consider tpAdd and bgpAdd during greedy join planning;
2. Extract a helper function to enumerate possible physical plans for connecting two subplans (one of which uses PhysicalOpRequest as root operator ). This helper function can be used for greedy join planners and DB-based join planners.

Consider tpAdd and bgpAdd in greedy join planning

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitor.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitorBase.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalOpFilter.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalPlanPrinter.java

>Add a corresponding logical operator and a corresponding physical operator. Begin with the logical one (because for implementing the physical one, you will need the logical one).
> 
> The class for the logical operator should be called `LogicalOpFilter`, it should go into the Java package `se.liu.ida.hefquin.engine.queryplan.logical.impl`, and it should implement the `UnaryLogicalOp` interface.
> 
> As an example of another such logical operator, take a look at `LogicalOpTPAdd`. You can essentially copy this class and replace its two member variables by a member variable of type `Expr` (i.e., exactly as you have it in the new executable operator in this PR here).
> 
> When you do this, you will notice that you also have to extend the `LogicalPlanVisitor` interface with an additional …

Filter Operators

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/simple/DPBasedJoinPlanOptimizer.java

Since the candidatePairs already contain two pairs in the opposite order, there is no need to create the plan twice with unaryOp

Duplicate plans were created in DPBasedJoinPlanOptimizer

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlanVisitor.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpFilter.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanPrinter.java

> You need to create a new class called `PhysicalOpFilter`. This class should go into the Java package `se.liu.ida.hefquin.engine.queryplan.physical.impl` and it should implement the `UnaryPhysicalOpForLogicalOp` interface.
> 
> It should have a `LogicalOpFilter` as a member variable, assigned through the constructor.
> 
> The `createExecOp` function that you need to implement in this class should create and return an `ExecOpFilter` and it can ignore the `inputVars` argument.
> 
> The `getExpectedVariables` function that you need to implement in this class should check that the `inputVars` argument is an array of length 1 (otherwise throw an IllegalArgumentException) and, then, it should simply return the one `ExpectedVariables` object contained in that array.
Done as far as my current …

Physical Filter Operator

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/CardinalityEstimationUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/CostEstimationUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/utils/PhysicalPlanWithCostUtils.java

Extend the implementation of CostEstimationUtils.getEstimates and CostEstimationUtils.getEstimates: 
instead of creating CompletableFutures for all given plans, takes plans in batches (temporarily set the batch size as 50).

Address issue #168

---

src/main/java/se/liu/ida/hefquin/engine/data/utils/JoiningIterableForSolMaps.java
src/main/java/se/liu/ida/hefquin/engine/data/utils/JoiningIteratorForSolMaps.java
src/main/java/se/liu/ida/hefquin/engine/data/utils/SolutionMappingUtils.java
src/test/java/se/liu/ida/hefquin/engine/data/utils/JoiningIteratorForSolMapsTest.java

This PR adds `JoiningIteratorForSolMaps` and `JoiningIterableForSolMaps` where the latter uses the former. These helper classes can be used to enumerate the result of a join of two collections of solution mappings. This is a streaming alternative to [SolutionMappingUtils.nestedLoopJoin](https://github.com/LiUSemWeb/HeFQUIN/blob/f21134e657c875705ee14d8269f0a38ff25dc656/src/main/java/se/liu/ida/hefquin/engine/data/utils/SolutionMappingUtils.java#L134) (see PR #183).
/cc @scferrada @JulietteVV

Adds JoiningIteratorForSolMaps and JoiningIterableForSolMaps

---

src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java

I believe this is it. The ElementUnion/ElementGroup goes through each pattern from the getSubPatterns() method of the SPARQLUnionPattern/SPARQLGraphPattern and adds it after converting it by calling the convertToJenaElement-method.

Recursive convertToJenaElement for Union and Group Patterns.

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpLocalToGlobal.java

This should implement the Local2Global functionality assuming I remembered it correctly that it is the sink object which the 'result' is sent to. The preferredInputBlockSize and _concludeExecution methods have been left empty for now.

LocalToGlobal operator functionality.

---

src/main/java/se/liu/ida/hefquin/engine/datastructures/impl/SolutionMappingsIndexNoJoinVars.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/BaseForExecOpIndexNestedLoopsJoinWithRequestOps.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpParallelMultiwayLeftJoin.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlanVisitor.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpParallelMultiLeftJoin.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalPlanConverterImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanPrinter.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinBRTPFTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithFILTERTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithUNIONTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUESTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpIndexNestedLoopsJoinSPARQLTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpIndexNestedLoopsJoinTPFTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpParallelMultiwayLeftJoinTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/TestsForTPAddAlgorithms.java

Implement ExecOpParallelMultiwayLeftJoin: 
- Create indexes structure based on the number of joinVariables for each optional part;
- Implement a runnable worker to populate intermediate results into the index; 
- Produce final output by merging intermediate results (left out join)

Parallel multiway left join

---

src/main/java/se/liu/ida/hefquin/engine/utils/CypherQueryUtils.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/CypherMatchQuery.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/UnwindIterator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/CypherMatchQueryImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/UnwindIteratorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/ListMembershipCondition.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryBuilder.java

This PR adds the `UnwindIterator` interface and its implementation. The interface `CypherMatchQuery` now provides a method to obtain its iterators.

Unwind support

---

src/main/java/se/liu/ida/hefquin/engine/federation/GraphQLEndpoint.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/impl/GraphQLEndpointImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/impl/GraphQLEndpointInitializerImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/utils/SPARQL2GraphQLHelper.java
src/test/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/GraphQLRequestProcessorImplTest.java

Necessary fix that makes sure no types are initialized in GraphQLEndpoint initializer unless they have the ID field. Removes initialized fields if they would lead to such a removed type.

GraphQLEndpoint initializer now checks that types have id

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/CypherMatchQueryImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/UnwindIteratorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/PropertyValueConditionWithVar.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/CountLargerThanZeroReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/VariableGetItemReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryBuilder.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

This PR adds translations for triple patterns without variables, and updates the rules that require the use of UNWIND. Tests are also updated and bugs were fixed.
Since this PR already handles a lot, after this is merged it will come a second one that handles nested triple pattern translation, and the special rules for variables with boundedness properties.

Translations with unwind

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalOpUtils.java

Since these are algorithms that work on operators and not operators in themselves, I found it fitting to add them to LogicalOpUtils as both their inputs and outputs are logical ops.
In HeFQUIN, the class 'LogicalOpRequest' which I assume is the request operator has in addition to a federation member also a 'reqtype'. Is the ExpectedVariables in ReqType what I should be looking at when seeing what sort of pattern the Request is requesting?

RW and rewriteReqOf

---

src/main/java/se/liu/ida/hefquin/engine/utils/CypherQueryUtils.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/CypherMatchQuery.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/CypherUnionQuery.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/ReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/CypherMatchQueryImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/CypherUnionQueryImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/condition/JoinCondition.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/EdgeMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/NodeMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/AllPropertyValuesReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/CountLargerThanZeroReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/EmptyReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/FilteredPropertiesReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/LabelsReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/LiteralValueReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/PropertyListReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/PropertyValueReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/RelationshipTypeReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/TripleMapReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/VariableGetItemReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/returns/VariableReturnStatement.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryBuilder.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryCombinator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherUtils.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

Adds initial support to BGP translations to Cypher. It does not support joins on the predicate position, since I need to do some refactor to be able to reproduce the function from the paper. This refactor will contain a new interface: `CypherExpression` that will replace some of the strings that are being used, specially in `UnwindIteratorImpl`.
There's initial test on leveraging boundedness properties, as well as on capturing joins on literals.

Bgp translation

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/CypherMatchQuery.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/CypherMatchQueryImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/GetItemExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/UnwindIteratorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryCombinator.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

This PR contains the version of the combination function that allows any kinds of joins. There is just one test so far, I can add some more.
I make extensive use of the `stream` framework for map/filter/match efficiently over different sets, I think I've read somewhere here that we shouldn't really use it, so I can change this if necessary, although the code is complicated enough as it is.

Complete combine function

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryCombinator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherVarGenerator.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

Removes the getVarFor and getEdgeVarsFor methods from the Variable Generator, thus changing the combination function and the translation rules.

Removes Gamma functions

---

ExampleFederation.ttl
src/main/java/se/liu/ida/hefquin/cli/modules/ModFederation.java
src/main/java/se/liu/ida/hefquin/vocabulary/FD.java

This PR extends the CLI with a new argument (`--federationDescription`) which can be used to load an RDF description of the federation members. With this, it is not necessary anymore to declare all the federation members separately using `--considerSPARQLEndpoint` etc arguments.
The PR also adds an example Turtle file which illustrates how such RDF descriptions need to look like. The RDF vocabulary used for such descriptions is just an initial proposal and may change.
This PR presents a basis for addressing #24.
/cc @chengsijin0817 @scferrada

Loading of RDF file with federation members

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/CypherExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/AliasedExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/CountLargerThanZeroExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/CypherVar.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/EXISTSExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/EqualityExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/GetItemExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/KeysExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/LabelsExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/LiteralExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/MembershipExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/PropertyAccessExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/PropertyAccessWithVarExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/TripleMapExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/TypeExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/UnwindIteratorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/VariableIDExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/expression/VariableLabelExpression.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/EdgeMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/NodeMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherExpressionVisitor.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherQueryBuilder.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherUtils.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/VariableReplacementVisitor.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

Hi, I wanted to have a PR with both the join rewriting and the path merging, but I had to add a Visitor for the first one since most `CypherExpression`s are recursive, so this PR is all about making explicit joins implicit.

Adds code for join rewriting of Cypher Queries

---

ExampleFederation.ttl
dbpedia/vocabularyMappings.nt
src/main/java/se/liu/ida/hefquin/cli/modules/ModFederation.java
src/main/java/se/liu/ida/hefquin/vocabulary/FD.java

- Extend the ExampleFederation with a property for specifying the path to vocabulary mappings
- Update the method parseFedDescr
- Add an example 'vocabularyMappings' file for testing
In the method 'parseFedDescr', only the federation members with a SPARQL endpoint are extended for considering vocabulary mappings when parsing federation descriptions, at the moment.
If it looks okay, I can use the same implementation for parsing all different types of federation members.

Extend federation description

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslator.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SPARQLStar2CypherTranslatorImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/EdgeMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/query/impl/match/PathMatchClause.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/CypherExpressionVisitor.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/LabeledGraph.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/LabeledGraphBuilder.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/VariableReplacementVisitor.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/LabeledGraphTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/SPARQLStar2CypherTranslatorTest.java

This PR introduces a method for the translator object, which takes a set of `NodeMatchClause` and `EdgeMatchClause` and merges them into longer path patterns (`PathMatchPattern`).
To implement this method, all Match clauses are added into a "graph pattern", which is in class `LabeledGraph`. This class provides methods for finding the longest (simple undirected) path in the graph, and removing paths from the graph.
This PR also fixes a bug in the visitor pattern, where objects in lists need to be extracted in the reverse order they were put in the stack.

Merge of Path Patterns

---

src/main/java/se/liu/ida/hefquin/engine/data/impl/VocabularyMappingImpl.java

Fix an issue in result rewriting, specifically for variables that are bound to RDF literals.
Here is an example query for reproducing the issue:
the execution of this query does not terminate if '[ApplyVocabularyMappings](https://github.com/LiUSemWeb/HeFQUIN/blob/b5ee241745cad089cb4a8e91ee8e6baef73ddf5c/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/LogicalOptimizerImpl.java#L23)' is enabled.
```
SELECT * WHERE {
SERVICE <http://dbpedia.org/sparql> { 
<http://data.europa.eu/euodp/jrc-names/Adam_Maher> <http://www.w3.org/2000/01/rdf-schema#label> ?name 
}
}
```

Fix an issue in result rewriting

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/ApplyVocabularyMappings.java

Functionality for filter operations in the plan rewrite of ApplyVocabularyMappings. Necessary to get all the tests to run when building the package after uncommenting the lines required for the rewriting package build:
return createQueryOptimizerWithoutOptimization(ctxt); uncommented in HeFQUINEngineConfig.java
heuristics.add( new ApplyVocabularyMappings()); uncommented in LogicalOptimizerImpl.java

ApplyVocabularyMapping can now handle plans containing filter operators.

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUES.java

Consider the case where the given solution mapping does not have any join variables with the triple pattern

ExecOpBindJoinSPARQLwithVALUES

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/PushJoinUnderUnionWithRequests.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/PushJoinUnderUnionWithRequestsTest.java

This PR adds another heuristics.   /cc @chengsijin0817 
In cases in which there are unions with requests under joins (which may happen only if we do not use UnionPullUp), this heuristics turns the requests into xxAdd operators with the previous join arguments as subplans. The rationale of this heuristics is that it allows us to use bind joins and index nested loops joins in cases in which otherwise only local join algorithms (e.g., hash join) could be used. In this sense, the effect of this heuristics is similar to that of UnionPullUp, but without pulling out unions completely and, thus, without producing a great number of join subplans.
For instance, consider the following plan.
```
mj(
req_fm1^(s,p,?x),
mu(
req_fm2^(?x,p2,?y),
req_fm3^(?x,p2,?y)
),
mu(
req_fm2^(?y,p3,?z), …
```

Adds PushJoinUnderUnionWithRequests heuristics

---

src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java

'printQueryProcTime': print out statistics about the query processing time in one line

Add a cmd argument: 'printQueryProcTime'

---

src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/utils/LabeledGraph.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/LabeledGraphTest.java

Fixes a bug on the `longestPath` method, where it would only go back one step after finding a dead end. Now it goes back however many steps necessary to find a new path.

Longest path fix

---

src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/NaryExecutableOp.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpMultiwayUnion.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/NaryExecutableOpBase.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/pushbased/PushBasedExecPlanTaskForNaryOperator.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlanVisitor.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpMultiwayUnion.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalOpConverter.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalPlanConverterImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanPrinter.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/compiler/PullBasedQueryPlanCompilerImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/compiler/PushBasedQueryPlanCompilerImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/compiler/TaskBasedQueryPlanCompilerBase.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpMultiwayUnionTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/TestsForUnionAlgorithms.java

closes #123 
@chengsijin0817 Just for your information, I have implemented a physical operator for multiway unions. This way, we do not anymore need to convert logical multiway unions into a left-deep trees of binary unions on the physical plan level. This has two advantages: First, we need only one thread per multiway union. Second, the printed plans are easier to read.

Adds physical + executable operator for multiway unions

---

src/main/java/se/liu/ida/hefquin/cli/modules/ModFederation.java
src/main/java/se/liu/ida/hefquin/engine/federation/catalog/FederationDescriptionReader.java
src/test/java/se/liu/ida/hefquin/engine/federation/catalog/FederationDescriptionReaderTest.java

Moves the functionality of reading an RDF description of a federation out of `ModFederation` into a separate class (`FederationDescriptionReader`).
/cc @chengsijin0817

adds FederationDescriptionReader

---

src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfig.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanFactory.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRNumberOfRequests.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/CardinalityBasedGreedyJoinPlanOptimizerImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/CostModelBasedGreedyJoinPlanOptimizerImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedJoinPlanOptimizer.java

Implements a query optimizer that builds left-deep query plans, for which it uses a greedy approach to determine the join order based on cardinality estimation, and then choose the physical algorithm according to the estimated number of requests to execute the join.

Cardinality based greedy join plan optimizer

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRBasedCostFunctionForPlan.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CFRBasedParallelismCostFunctionForPlan.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CostFunctionForPlan.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CostModelImpl.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/costmodel/CostModelImplTest.java

When aggregating cost values in the cost model, avoid counting duplicates by skipping the subquery that has already been visited.

Avoid counting duplicates in cost model

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/RemovePairsOfG2lAndL2g.java

If a pair of g2l and l2g operators use the same vocabulary mapping, these two operators can be omitted

Remove pairs of G2l and L2g operators

---

src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/LogicalOptimizerImpl.java

To get correct cardinality estimation, 'CardinalityBasedJoinOrderingWithRequests' needs to be applied after 'ApplyVocabularyMappings'

Apply heuristics

---

src/main/java/se/liu/ida/hefquin/engine/query/impl/QueryPatternUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanUtils.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitor.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlanVisitorBase.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalOpExtend.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalPlanPrinter.java
src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalOpConverter.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/MergeRequests.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/srcsel/ServiceClauseBasedSourcePlannerImpl.java
src/main/java/se/liu/ida/hefquin/jenaintegration/sparql/engine/main/OpExecutorHeFQUIN.java

To handle the BIND clause of a SPARQL query, a new operator has been added:
- Add a logical operator for OpExtend: LogicalOpExtend
- In logical plan optimization, merge the BIND clause into a request operator if that request is for a SPARQL endpoint.
With this new operator, the issue mentioned [here](https://github.com/MaastrichtU-IDS/federatedQueryKG/issues/9) is partially solved (i.e., A SPARQL query with BIND clause can be answered over SPARQL endpoints).
TODOs: For complete support of BIND clause, the implementation of the physical operator and executable operator for OpExtend still needs to be done.

Handle BIND clause in logical plan: OpExtend

---

ExampleLPG2RDF.ttl
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/EdgeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedEdgeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleEdgeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/exceptions/UnSupportedEdgeLabelException.java
src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/EdgeLabelMappingToURIsImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedEdgeLabelMappingToURIsImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleEdgeLabelMappingToURIsImplTest.java

Add CombinedEdgeLabelMapping and its tests
Encapsulate creating EdgeLabelMapping into different functions to avoid duplicate code 
Add UnSupportedEdgeLabelException

Add CombinedEdgeLabelMapping

---

src/main/java/se/liu/ida/hefquin/cli/RunBGPOverNeo4j.java
src/main/java/se/liu/ida/hefquin/cli/modules/ModLPG2RDFConfiguration.java

Add command-line argument for passing LPG2RDFConfiguration description.

Add LPG2RDFConfiguration command-line argument

---

ExampleLPG2RDF.ttl
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedNodeLabelMappingImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToLiteralsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/NodeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedNodeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleNodeLabelMappingToLiteralsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleNodeLabelMappingToURIsImpl.java
src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/exceptions/UnSupportedNodeLabelException.java
src/main/java/se/liu/ida/hefquin/vocabulary/LPG2RDF.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedNodeLabelMappingImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReaderTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/RegexBasedNodeLabelMappingToURIsImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleNodeLabelMappingToLiteralsImplTest.java
src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SingleNodeLabelMappingToURIsImplTest.java

Add SingleLiteralNodeLabelMapping, SingleIRINodeLabelMapping, RegexIRINodeLabelMapping, and CombinedNodeLabelMapping classes and their tests.

Make NodeLabelMapping more flexible

---

pom.xml
src/main/java/se/liu/ida/hefquin/engine/data/utils/JenaResultSetUtils.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/BRTPFInterface.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/TPFInterface.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/BRTPFInterfaceImpl.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/iface/TPFInterfaceImpl.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/BRTPFRequestProcessorImpl.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/SPARQLRequestProcessorImpl.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorBase.java
src/main/java/se/liu/ida/hefquin/engine/federation/access/impl/reqproc/TPFRequestProcessorImpl.java

This PR upgrades the code base to version 4.10 of Jena. The main change that was necessary was to rewrite all the code that was based on Jena's HttpQuery class (which, in turn, was based on the Apache HttpClient library). The newly written code uses Jena's new HTTP-related helper functionality, which is based on the HttpClient API that was introduced in Java 11.
Note that, after doing a `git pull`, you may need to have your IDE update the Maven-related stuff for the HeFQUIN project in your IDE. For Eclipse, I had to right-click on the project, select the menu items "Maven" -> "Update project ..." in the pop-up menu, and then simply click "Ok" in the dialog that shows up.

Upgrade to Jena 4.10

---

src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java
src/main/java/se/liu/ida/hefquin/cli/modules/ModPlanPrinting.java

@huanyu-li this one is for you. It adds a dedicated module of CLI arguments related to the printing of plans and moves the current arguments for plan printing into this module. This new module can now serve as a basis for additional arguments that you might add during the hackathon.

Adds a module for CLI arguments for plan printing

---

src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java
src/main/java/se/liu/ida/hefquin/cli/modules/ModEngineConfig.java
src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfigReader.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/QueryProcContext.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImpl.java
src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/compiler/QueryPlanCompilerBase.java
src/test/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfigReaderTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/iterbased/TestUtils.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpParallelMultiwayLeftJoinTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestTPFWithTranslationTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestTPFatTPFServerTest.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/TestsForTPAddAlgorithms.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/TestsForTPAddAlgorithmsWithTranslation.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImplTest.java
src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/srcsel/SourcePlannerImplTestBase.java

@huanyu-li  Here is another one for you. This PR adds a CLI argument (`--skipExecution`) with which users of the CLI tool can print the query plans without actually executing the query.

CLI Argument to skip the query execution

---

src/test/java/se/liu/ida/hefquin/engine/EngineTestBase.java
src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpParallelMultiwayLeftJoinTest.java

twoOptsWithNoJoinPartners(): No matching join-values in either.
twoOptsWithOneJoinPartnerInBoth(): Base test created by Olaf, renamed to be consistent with the other names.
twoOptsWithOneJoinPartnerInOne(): Only one of the two OPTIONAL has a matching join-value.
twoOptsWithOneJoinPartnerInOneMirrored(): Same as the above, but it is the other one.
twoOptsWithIdenticalNonOptionals(): Contains multiple solution mappings with the same join-value as an input, as well as one mapping with a join-value which finds no matches in the OPTIONALs.
twoOptsWithMultiplePartnersInBoth(): Multiple triples in both OPTIONAL clauses have matching join-values.
twoOptsWithMultiplePartnersInBothAndMultipleNonOptionals(): The most complicated and thorough test. Multiple triples in both OPTIONAL clauses have …

Left Join Tests

---

.github/workflows/docker.yml
.github/workflows/maven.yml

This workflow is triggered when a release is published, and builds and publishes the corresponding docker image in `ghcr.io` with the tag `latest` as well as any tags provided for the release.

add workflow to publish docker image 

---

pom.xml

This resolves #368
The version can now be updated correctly across all `pom.xml` files using:
```bash
mvn versions:set -DnewVersion=x.y.z -DgenerateBackupPoms=false
```

remove property project.version, use default instead

---

hefquin-base/pom.xml
hefquin-cli/pom.xml
hefquin-engine/pom.xml
hefquin-graphqlconnector/pom.xml
hefquin-pgconnector/pom.xml
hefquin-service/pom.xml
pom.xml

First version of metadata required in pom.xml.

Maven central repo requirements

---

pom.xml

This option simplifies the structure of the generated javadoc and makes it possible to to support search functionality when embedding the javadocs in an iframe.

add --no-module-directories to pom

---

hefquin-base/src/test/java/se/liu/ida/hefquin/base/query/utils/QueryPatternUtilsTest.java
hefquin-base/src/test/java/se/liu/ida/hefquin/query/QueryPatternUtilsTest.java

This PR adds basic tests for `QueryPatternUtils` (see issue #289)

add basic tests for QueryPatternUtils

---

ExampleFederation.ttl
hefquin-service/src/main/resources/DefaultFedConf.ttl
hefquin-service/src/test/java/se/liu/ida/hefquin/service/InspectServletTest.java
hefquin-service/src/test/resources/TestFedConf.ttl

This PR updates the namespace used for the federation description vocabulary in the `hefquin-service` resource files and the federation description example file (`ExampleFederation.ttl`).
Resolves issue #436

update namespace used in federation descriptions

---

hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBind.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpFilter.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpGlobalToLocal.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpLocalToGlobal.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/UnaryExecutableOpBaseWithoutBlocking.java

This PR adds `UnaryExecutableOpBaseWithoutBlocking` as a base class for unary operators that do _not_ need to process the input solution mappings in batches (the filter operator is a typical example). For such operators, this base class implements the functionality to still consume every list of input solution mapping in batches.
The purpose of consuming the input list of solution mappings in batches is to increase inter-operator parallelism in the executable plans, in particular in cases in which the input list is huge. If such a huge input list was first processed completely to collect all the output solution mappings for the parent operator in the plan, then the parent operator may idle. Of course, it is also possible to directly send all output solution mappings individually to the …

increase inter-operator parallelism

---

hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/info/QueryPlanProperty.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/info/QueryPlanningInfo.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/BaseForLogicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalPlanWithBinaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalPlanWithNaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalPlanWithNullaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/LogicalPlanWithUnaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/BaseForTextBasedPlanPrinters.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/TextBasedLogicalPlanPrinterImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/CardinalityEstimator.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/RequestBasedCardinalityEstimator.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/CardinalityBasedJoinOrderingBase.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/CardinalityBasedJoinOrderingWithRequests.java
hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/CardinalityBasedJoinOrderingBaseTest.java
hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/UnionPullUpTest.java

This PR is the beginning of work on a more systematic approach to capture query-planning-related information about query plans. In particular, the PR extends the `LogicalPlan` interface with a method to obtain a `QueryPlanningInfo` object for the corresponding (logical) plan. This object is meant to be populated with properties of the plan (such as the estimated cardinality of the query result produced by the plan). To demonstrate how this will work, the PR also adds an initial version of a `CardinalityEstimator` (to be refined in a future PR). Additionally, the PR extends the logical plan printer to print the plan properties (such as cardinality estimates) at each level of the plan. The result of these extensions can be seen in the following example printout of a logical plan (notice the …

Adds QueryPlanningInfo to logical plans

---

CHANGELOG.md
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/LogicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/logical/impl/BaseForLogicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/PhysicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/BaseForPhysicalPlan.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpParallelMultiLeftJoin.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalPlanWithBinaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalPlanWithNaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalPlanWithNullaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalPlanWithUnaryRootImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/LogicalToPhysicalPlanConverterImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/PhysicalPlanFactory.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/TextBasedPhysicalPlanPrinterImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/CardinalityBasedGreedyJoinPlanOptimizerImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/CostModelBasedGreedyJoinPlanOptimizerImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/poptimizer/simple/DPBasedJoinPlanOptimizer.java
hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/loptimizer/heuristics/UnionPullUpTest.java

This is the next step following PR #455.
This PR:
1. extends the `PhysicalPlan` interface with a method to obtain a `QueryPlanningInfo` object for the corresponding (physical) plan,
2. extends the physical plan printer to print the content of such `QueryPlanningInfo` objects at each level of the plan, and
3. extends both the `LogicalToPhysicalPlanConverterImpl` and `PhysicalPlanFactory` such that `QueryPlanningInfo` objects are carried over when converting a logical plan into a physical one.

Adds QueryPlanningInfo to physical plans

---

hefquin-cli/src/main/java/se/liu/ida/hefquin/cli/RunQueryWithoutSrcSel.java
hefquin-cli/src/main/java/se/liu/ida/hefquin/cli/modules/ModPlanPrinting.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineBuilder.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfigReader.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/ExecutablePlanPrinter.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryplan/utils/TextBasedExecutablePlanPrinterImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/QueryPlanner.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImpl.java
hefquin-engine/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/planning/QueryPlannerImpl.java
hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/HeFQUINEngineConfigReaderTest.java
hefquin-engine/src/test/java/se/liu/ida/hefquin/engine/queryproc/impl/QueryProcessorImplTest.java

This PR provides a first implementation of a text based printer for executable plans (see https://github.com/LiUSemWeb/HeFQUIN/issues/27).
The printer currently supports only `PushBasedExecutablePlanImpl`. Also note that the `toString()` methods have not yet been implemented for the executable operators (see https://github.com/LiUSemWeb/HeFQUIN/issues/210), which means the printer defaults to printing class reference + hash code.
@hartig, I was also experimenting with implementing the visitor pattern for executable plans. This would provide more control over how the operators are actually printed, but the executable operators aren't available from the tasks in the current code. Thoughts?

Add executable plan printer
